apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - image: ghcr.io/dysnomia-studio/sonarqube:main
        name: sonarqube
        ports:
        - containerPort: 9000
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 25m
            memory: 2000Mi
          limits:
            cpu: 2000m
            memory: 4000Mi
        env:
          - name: SONAR_JDBC_URL
            value: jdbc:postgresql://sonarqube-database-rw.sonarqube.svc.cluster.local/sonarqube
          - name: SONAR_JDBC_USERNAME
            valueFrom:
              secretKeyRef:
                name: sonarqube-database-app
                key: username
                optional: false
          - name: SONAR_JDBC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sonarqube-database-app
                key: password
                optional: false
          - name: SONAR_WEB_JAVAADDITIONALOPTS 
            value: "-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-25.9.0.jar=web"
          - name: SONAR_CE_JAVAADDITIONALOPTS 
            value: "-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-25.9.0.jar=ce"
      imagePullSecrets:
      - name: github
