apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sonarqube-database
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5

  bootstrap:
    initdb:
      database: sonarqube
      owner: sonarqube

  enableSuperuserAccess: true

  resources:
    requests:
      memory: "512Mi"
      cpu: 250m
    limits:
      memory: "1Gi"
      cpu: '1'

  storage:
    size: 5Gi
