apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile-server
  namespace: seafile
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: seafile-server
  template:
    metadata:
      labels:
        app: seafile-server
    spec:
      containers:
      - image: seafileltd/seafile-pro-mc:12.0.16
        name: seafile-server
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
            memory: 2000Mi
          limits:
            cpu: 3000m
            memory: 8000Mi
        volumeMounts:
        - name: data
          mountPath: /shared
        ports:
          - containerPort: 80
        env:
          - name: DB_HOST
            value: seafile-mariadb.seafile.svc.cluster.local
          - name: DB_ROOT_PASSWD
            valueFrom:
              secretKeyRef:
                name: seafile-5464h59g97
                key: mysql-password
                optional: false
          - name: TIME_ZONE
            value: Europe/Paris
          - name: SEAFILE_ADMIN_EMAIL
            valueFrom:
              secretKeyRef:
                name: seafile-5464h59g97
                key: admin-mail
                optional: false
          - name: SEAFILE_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: seafile-5464h59g97
                key: admin-password
                optional: false
          - name: JWT_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: seafile-5464h59g97
                key: jwt-private-key
                optional: false


      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: longhorn-pvc-seafile-server-data
