---
version: 2
registries:
  github:
    type: docker-registry
    url: https://ghcr.io
    username: ${{ secrets.GHP_USER }}
    password: ${{ secrets.GHP_TOKEN }}
updates:
  - package-ecosystem: "docker"
    directory: "/"
    registries: "*"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/dysnomia-wiki"
    registries: "*"
    schedule:
      interval: "monthly"
# lastUpdate 2024-06-06 16:25:03
