apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: security
  namespace: kube-system
spec:
  headers:
    frameDeny: true
    customFrameOptionsValue: sameorigin
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true

    #HSTS Configuration
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000

    # Hide powered by headers
    customResponseHeaders:
      x-powered-by: ""