apiVersion: v1
kind: Namespace
metadata:
  name: homepage
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: default
  source:
    chart: homepage
    repoURL: https://jameswynn.github.io/helm-charts
    targetRevision: 2.0.1
    helm:
      releaseName: homepage
      valuesObject:
        bookmarks:
          - Developer:
              - Github:
                  - abbr: GH
                    href: https://github.com/
        services:
          - System dashboards:
              - ArgoCD:
                  href: https://argocd-server.argocd.svc.cluster.local/
                  description: ArgoCD dashboard
              - Longhorn:
                  href: http://longhorn-frontend.longhorn-system-restoration.svc.cluster.local/
                  description: Longhorn dashboard
              - PGWatch:
                  href: http://pgwatch-ui.monitoring.svc.cluster.local/
                  description: PGWatch dashboard
              - Traefik:
                  href: http://traefik-private.kube-system.svc.cluster.local/
                  description: Traefik dashboard

          - Apps:
              - Grafana:
                  href: http://grafana.kube-system.svc.cluster.local/login
                  description: 📊 Stats 📈

          - My Third Group:
              - My Third Service:
                  href: http://localhost/
                  description: Homepage is 😎
        widgets:
          # show the kubernetes widget, with the cluster summary and individual nodes
          - kubernetes:
              cluster:
                show: true
                cpu: true
                memory: true
                showLabel: true
                label: "cluster"
              nodes:
                show: true
                cpu: true
                memory: true
                showLabel: true
          - search:
              provider: duckduckgo
              target: _blank
        kubernetes:
          mode: cluster
        settings:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'homepage'
  syncPolicy:
    automated: {}
---
apiVersion: v1
kind: Service
metadata:
  name: home
  namespace: homepage
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/name: homepage
  type: ClusterIP