apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  ignoreDifferences:
  - group: "*"
    kind: "MutatingWebhookConfiguration"
    jqPathExpressions:
    - .webhooks[].clientConfig.caBundle
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.28.1
    helm:
      releaseName: vault
      valuesObject:
        global:
          enabled: true
          tlsDisable: false

        injector:
          enabled: true

          resources:
              requests:
                memory: 256Mi
                cpu: 250m
              limits:
                memory: 256Mi
                cpu: 250m

        server:
          # These Resource Limits are in line with node requirements in the
          # Vault Reference Architecture for a Small Cluster
          resources:
            requests:
              memory: 8Gi
              cpu: 2000m
            limits:
              memory: 16Gi
              cpu: 2000m

          # For HA configuration and because we need to manually init the vault,
          # we need to define custom readiness/liveness Probe settings
          readinessProbe:
            enabled: true
            path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
          livenessProbe:
            enabled: true
            path: "/v1/sys/health?standbyok=true"
            initialDelaySeconds: 60

          extraEnvironmentVars:
            VAULT_CACERT: /vault/userconfig/tls-ca/tls.crt

          # extraVolumes is a list of extra volumes to mount. These will be exposed
          # to Vault in the path `/vault/userconfig/<name>/`.
          extraVolumes:
            - type: secret
              name: tls-server
            - type: secret
              name: tls-ca

          # This configures the Vault Statefulset to create a PVC for audit logs.
          # See https://www.vaultproject.io/docs/audit/index.html to know more
          auditStorage:
            enabled: true

          standalone:
            enabled: false

          # Run Vault in "HA" mode.
          ha:
            enabled: true
            replicas: 3
            raft:
              enabled: true
              setNodeId: true

              config: |
                ui = true
                listener "tcp" {
                  address = "[::]:8200"
                  cluster_address = "[::]:8201"
                  tls_cert_file = "/vault/userconfig/tls-server/tls.crt"
                  tls_key_file = "/vault/userconfig/tls-server/tls.key"
                }

                storage "raft" {
                  path = "/vault/data"
                    retry_join {
                    leader_api_addr = "https://vault-0.vault-internal:8200"
                    leader_ca_cert_file = "/vault/userconfig/tls-ca/tls.crt"
                    leader_client_cert_file = "/vault/userconfig/tls-server/tls.crt"
                    leader_client_key_file = "/vault/userconfig/tls-server/tls.key"
                  }
                  retry_join {
                    leader_api_addr = "https://vault-1.vault-internal:8200"
                    leader_ca_cert_file = "/vault/userconfig/tls-ca/tls.crt"
                    leader_client_cert_file = "/vault/userconfig/tls-server/tls.crt"
                    leader_client_key_file = "/vault/userconfig/tls-server/tls.key"
                  }
                  retry_join {
                    leader_api_addr = "https://vault-2.vault-internal:8200"
                    leader_ca_cert_file = "/vault/userconfig/tls-ca/tls.crt"
                    leader_client_cert_file = "/vault/userconfig/tls-server/tls.crt"
                    leader_client_key_file = "/vault/userconfig/tls-server/tls.key"
                  }
                }

                service_registration "kubernetes" {}

        # Vault UI
        ui:
          enabled: true
          serviceType: "LoadBalancer"
          serviceNodePort: null
          externalPort: 8200

          # For Added Security, edit the below
          #loadBalancerSourceRanges:
          #   - < Your IP RANGE Ex. 10.0.0.0/16 >
          #   - < YOUR SINGLE IP Ex. 1.78.23.3/32 >

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'vault'
  syncPolicy:
    automated: {}
