apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: fs-trim
  namespace: longhorn-system-restoration
spec:
  concurrency: 1
  cron: '0 4 * * *'
  groups:
  - default
  labels: {}
  name: fs-trim
  retain: 0
  task: filesystem-trim
