apiVersion: apps/v1
kind: Deployment
metadata:
  name: downstatus
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: downstatus
  template:
    metadata:
      labels:
        app: downstatus
    spec:
      containers:
      - image: ghcr.io/dysnomia-studio/downstatus:main
        name: downstatus
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
          - name: AppSettings__ConnectionString
            valueFrom:
              secretKeyRef:
                name: downstatus-7g48th8f59
                key: database
                optional: false
          - name: DYSNOMIA_COMMON_STATS_CONNECTIONSTRING
            valueFrom:
              secretKeyRef:
                name: stats-writer-credentials-8ckkfd9ff2
                key: connectionstring
                optional: false
      imagePullSecrets:
      - name: github