apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: elanis-cdn-ingressroute

spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`kubernetest.dysnomia.studio`)
    kind: Rule
    services:
    - name: elanis-cdn-svc
      port: 80
    tls:
      certResolver: le