apiVersion: apps/v1
kind: Deployment
metadata:
  name: factory-server-ptb
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: factory-server-ptb
  template:
    metadata:
      labels:
        app: factory-server-ptb
    spec:
      containers:
      - image: ghcr.io/dysnomia-studio/factory-game-server:develop
        name: factory-server-ptb
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
          - name: PUBLISHER_KEY
            valueFrom:
              secretKeyRef:
                name: steam-hdcdk47mmg
                key: dysnomia-publisher-key
                optional: false
          - name: APP_ID
            valueFrom:
              secretKeyRef:
                name: steam-hdcdk47mmg
                key: factory-appid
                optional: false

          - name: PG_USER
            valueFrom:
              secretKeyRef:
                name: factory-server-ptb-database-b9gt9gbgm6
                key: username
                optional: false
          - name: PG_HOST
            valueFrom:
              secretKeyRef:
                name: factory-server-ptb-database-b9gt9gbgm6
                key: hostname
                optional: false
          - name: PG_DB
            valueFrom:
              secretKeyRef:
                name: factory-server-ptb-database-b9gt9gbgm6
                key: database
                optional: false
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: factory-server-ptb-database-b9gt9gbgm6
                key: password
                optional: false
          - name: UNIT_TEST_CLIENT_TOKEN
            valueFrom:
              secretKeyRef:
                name: factory-server-ptb-database-b9gt9gbgm6
                key: unitTestKey
                optional: false
          - name: IS_DEV
            valueFrom:
              secretKeyRef:
                name: factory-server-ptb-database-b9gt9gbgm6
                key: dev
                optional: false

      imagePullSecrets:
      - name: github