apiVersion: v1
kind: Namespace
metadata:
  name: firezone
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firezone-data-pvc
  namespace: firezone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firezone-deployment
  namespace: firezone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firezone
  template:
    metadata:
      labels:
        app: firezone
    spec:
      containers:
      - name: firezone
        image: firezone/firezone
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 51830
          protocol: UDP
        env:
        - name: DEFAULT_ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: firezone-tm822hbdtm
              key: admin-mail
              optional: false 
        - name: DEFAULT_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: firezone-tm822hbdtm
              key: admin-password
              optional: false 
        - name: EXTERNAL_URL
          value: "https://fz.dysnomia.studio"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: firezone-tm822hbdtm
              key: secret-key-base # Generated by openssl rand -hex 64
              optional: false 
        - name: LIVE_VIEW_SIGNING_SALT
          valueFrom:
            secretKeyRef:
              name: firezone-tm822hbdtm
              key: live-view-signing-salt # Generated by openssl rand -base64 48
              optional: false 
        - name: COOKIE_SIGNING_SALT
          valueFrom:
            secretKeyRef:
              name: firezone-tm822hbdtm
              key: cookie-signing-salt # Generated by openssl rand -base64 48
              optional: false 
        - name: COOKIE_ENCRYPTION_SALT
          valueFrom:
            secretKeyRef:
              name: firezone-tm822hbdtm
              key: cookie-encryption-salt # Generated by openssl rand -base64 48
              optional: false 
        - name: GUARDIAN_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: firezone-tm822hbdtm
              key: guardian-secret-key # Generated by openssl rand -hex 64
              optional: false 
        - name: DATABASE_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: firezone-tm822hbdtm
              key: db-encryption-key # Generated by openssl rand -hex 64
              optional: false 
        - name: DATABASE_HOST
          value: postgres.dysnomia-apps.svc.cluster.local
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: firezone-tm822hbdtm
              key: database
              optional: false 
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: firezone-tm822hbdtm
              key: username
              optional: false 
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: firezone-tm822hbdtm
              key: password
              optional: false 
        - name: WIREGUARD_PORT
          value: '51830'
        volumeMounts:
        - mountPath: /var/lib/firezone
          name: firezone-data
        - mountPath: /var/firezone
          name: firezone-saml
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_MODULE"]
      volumes:
      - name: firezone-data
        persistentVolumeClaim:
          claimName: firezone-data-pvc
      - name: firezone-saml
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: firezone-service-vpn
  namespace: firezone
spec:
  type: LoadBalancer
  ports:
  - name: custom-udp
    protocol: UDP
    port: 51830
    targetPort: 51830
  selector:
    app: firezone
---
apiVersion: v1
kind: Service
metadata:
  name: firezone-service-http
  namespace: firezone
spec:
  ports:
  - name: http
    protocol: TCP
    port: 13000
    targetPort: 13000
  selector:
    app: firezone
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: firezone-ingressroute
  namespace: firezone
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`fz.dysnomia.studio`)
    kind: Rule
    services:
    - name: firezone-service-http
      port: 13000
    middlewares:
    - name: security
      namespace: dysnomia-apps
  tls:
    certResolver: le