apiVersion: apps/v1
kind: Deployment
metadata:
  name: galactae-client-01
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: galactae-client-01
  template:
    metadata:
      labels:
        app: galactae-client-01
    spec:
      containers:
      - image: ghcr.io/dysnomia-studio/galactae-client:Beta-0.10.7-rev.230303a
        name: galactae-client-01
        ports:
        - containerPort: 80
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "bash /var/www/applyEnvVariables.sh"]
        imagePullPolicy: Always
        env:
          - name: GALACTAE_SQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: galactae-website-gfkkg56t7b
                key: username
                optional: false
          - name: GALACTAE_SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: galactae-website-gfkkg56t7b
                key: hostname
                optional: false
          - name: GALACTAE_SQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: galactae-website-gfkkg56t7b
                key: database
                optional: false
          - name: GALACTAE_SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: galactae-website-gfkkg56t7b
                key: password
                optional: false

          - name: GALACTAE_01_SQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: galactae-01-2kg42mb29d
                key: username
                optional: false
          - name: GALACTAE_01_SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: galactae-01-2kg42mb29d
                key: hostname
                optional: false
          - name: GALACTAE_01_SQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: galactae-01-2kg42mb29d
                key: database
                optional: false
          - name: GALACTAE_01_SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: galactae-01-2kg42mb29d
                key: password
                optional: false

          - name: STATS_SQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: stats-writer-credentials-78b6m75km9
                key: username
                optional: false
          - name: STATS_SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: stats-writer-credentials-78b6m75km9
                key: hostname
                optional: false
          - name: STATS_SQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: stats-writer-credentials-78b6m75km9
                key: database
                optional: false
          - name: STATS_SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: stats-writer-credentials-78b6m75km9
                key: password
                optional: false

        volumeMounts:
        - name: galactae-client-00-config
          mountPath: "/var/www/config/"
          readOnly: true

        - name: galactae-client-00-config
          mountPath: "/var/www/app/views/gvars/"
          readOnly: true

      imagePullSecrets:
      - name: github
      volumes:
      - name: galactae-client-00-config
        configMap:
          name: galactae-client-00-config