apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaspar
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gaspar
  template:
    metadata:
      labels:
        app: gaspar
    spec:
      containers:
      - image: ghcr.io/elanis/gaspar:main
        name: gaspar
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
          - name: AppSettings__ConnectionString
            valueFrom:
              secretKeyRef:
                name: gaspar-49t9f58bmk
                key: database
                optional: false
          - name: DYSNOMIA_COMMON_STATS_CONNECTIONSTRING
            valueFrom:
              secretKeyRef:
                name: stats-writer-credentials-d78t565ckb
                key: connectionstring
                optional: false
      imagePullSecrets:
      - name: github