apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: ghcr.io/dysnomia-studio/grafana:main
        name: grafana
        ports:
        - containerPort: 3000
        env:
          - name: GF_INSTALL_PLUGINS
            value: 'petrslavotinek-carpetplot-panel'

          - name: DS_DMARCREPORTS_USERNAME
            valueFrom:
              secretKeyRef:
                name: grafana-bhc6hgmdk6
                key: username
                optional: false
          - name: DS_DMARCREPORTS_HOST
            value: 192.168.1.3
          - name: DS_DMARCREPORTS_DB
            value: dmarcreports
          - name: DS_DMARCREPORTS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-bhc6hgmdk6
                key: password
                optional: false

          - name: DS_LUMEN_USERNAME
            valueFrom:
              secretKeyRef:
                name: grafana-bhc6hgmdk6
                key: username
                optional: false
          - name: DS_LUMEN_HOST
            value: 192.168.1.3
          - name: DS_LUMEN_DB
            value: lumen
          - name: DS_LUMEN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-bhc6hgmdk6
                key: password
                optional: false

          - name: DS_STATS_USERNAME
            valueFrom:
              secretKeyRef:
                name: grafana-bhc6hgmdk6
                key: username
                optional: false
          - name: DS_STATS_HOST
            value: 192.168.1.3
          - name: DS_STATS_DB
            value: stats
          - name: DS_STATS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-bhc6hgmdk6
                key: password
                optional: false
        imagePullPolicy: Always
      imagePullSecrets:
      - name: github