apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - image: ghcr.io/elanis/portfolio:6.0.5
        name: portfolio
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: github
