apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: ghcr.io/dysnomia-studio/postgres:main
        name: postgres
        imagePullPolicy: Always
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-9fb927c68c
                key: password
                optional: false
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
      imagePullSecrets:
      - name: github
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: longhorn-pvc-postgres-data