apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi