---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kube-system

data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
    - job_name: 'blackbox'
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
       - targets:
          - http://www.achieve.games
          - http://achieve.games
          - https://achieve.games
          - https://www.achieve.games
          - http://alchemistry-leaderboard.dysnomia.studio/leaderboard/
          - https://alchemistry-leaderboard.dysnomia.studio/leaderboard/
          - http://www.elanis.eu
          - http://elanis.eu
          - https://elanis.eu
          - https://www.elanis.eu
          - http://www.elanis.fr
          - http://elanis.fr
          - https://elanis.fr
          - https://www.elanis.fr
      relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter.kube-system.svc.cluster.local:9115

    - job_name: 'pgwatch2'
      static_configs:
      - targets: ['pgwatch:9187']

    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
      - targets: ['localhost:9090']

    - job_name: 'traefik'
      static_configs:
      - targets: ['traefik-prometheus:9100']
