apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc-seafile-elasticsearch-data
  namespace: seafile
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi