apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: subapps
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - list:
      elements:
      - name: 'factory-server-ptb'
      - name: 'factory-server-prod'
  template:
    metadata:
      name: '{{.name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/Dysnomia-Studio/argocd-infra.git
        targetRevision: HEAD
        path: '{{.name}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'dysnomia-apps'
      syncPolicy:
        automated: {}