apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: subapps
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - list:
      elements:
      - name: 'achieve-games'
        env: prod
        visibility: public
      - name: 'alchemistry-leaderboard'
        env: prod
        visibility: public
      - name: 'cours-m1'
        env: prod
        visibility: public
      - name: 'dehash-me'
        env: prod
        visibility: public
      - name: 'devblog'
        env: prod
        visibility: public
      - name: 'discord-server-stats'
        env: prod
        visibility: task
      - name: 'dysnomia-website'
        env: prod
        visibility: public
      - name: 'dysnomia-wiki'
        env: prod
        visibility: public
      - name: 'elanis-cdn'
        env: prod
        visibility: public
      - name: 'factory-server-prod'
        env: prod
        visibility: public
      - name: 'factory-server-ptb'
        env: public-test
        visibility: public
      - name: 'galactae'
        env: all
        visibility: public
      - name: 'gaspar'
        env: prod
        visibility: public
      - name: 'homepage'
        env: all
        visibility: internal
      - name: 'lumen-server'
        env: prod
        visibility: public
      - name: 'monitoring'
        env: all
        visibility: internal
      - name: 'n8n'
        env: prod
        visibility: internal
      - name: 'portfolio'
        env: prod
        visibility: public
      - name: 'redmine'
        env: prod
        visibility: public
      - name: 'seafile'
        env: prod
        visibility: partial
      - name: 'sonarqube'
        env: prod
        visibility: public
  template:
    metadata:
      name: '{{.name}}'
      namespace: argocd
      labels: 
        environment: '{{.env}}'
        visibility: '{{.visibility}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Dysnomia-Studio/argocd-infra.git
        targetRevision: HEAD
        path: '{{.name}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true