apiVersion: v1
kind: Service
metadata:
  name: traefik-prometheus
  namespace: kube-system
spec:
  ports:
  - port: 9100
    targetPort: 9100
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik