apiVersion: v1
kind: Service
metadata:
  name: traefik-private
  namespace: kube-system
spec:
  ports:
  - name: prometheus
    port: 9100
    targetPort: 9100
  - name: ui
    port: 80
    targetPort: 9000
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik