apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elanis-cdn-tls
spec:
  secretName: elanis-cdn-tls-secret
  dnsNames:
    - 01.cdn.elanis.eu
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer