apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: discord-server-stats-database
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2

  bootstrap:
    initdb:
      database: discord-server-stats
      owner: discord-server-stats

  enableSuperuserAccess: true

  resources:
    requests:
      memory: "512Mi"
      cpu: 250m
    limits:
      memory: "2Gi"
      cpu: '1'

  storage:
    size: 8Gi
