apiVersion: apps/v1
kind: Deployment
metadata:
  name: achieve-games
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: achieve-games
  template:
    metadata:
      labels:
        app: achieve-games
    spec:
      containers:
      - image: ghcr.io/dysnomia-studio/achieve-games:1.2.0
        name: achieve-games
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1000m
            memory: 4000Mi
          limits:
            cpu: 2500m
            memory: 7000Mi
        env:
          - name: AppSettings__SteamAPIPublisherToken
            valueFrom:
              secretKeyRef:
                name: steam-hdcdk47mmg
                key: dysnomia-publisher-key
                optional: false
          - name: AppSettings__SteamWebAPIToken
            valueFrom:
              secretKeyRef:
                name: steam-hdcdk47mmg
                key: elanis-webapi-key
                optional: false

          - name: AppSettings__ConnectionString
            valueFrom:
              secretKeyRef:
                name: achieve-games-6f86m258df
                key: database
                optional: false
          - name: AppSettings__RedirectURI
            valueFrom:
              secretKeyRef:
                name: achieve-games-6f86m258df
                key: redirecturi
                optional: false
          - name: AppSettings__GithubToken
            valueFrom:
              secretKeyRef:
                name: achieve-games-6f86m258df
                key: githubtoken
                optional: false
          - name: AppSettings__DiscordToken
            valueFrom:
              secretKeyRef:
                name: achieve-games-6f86m258df
                key: discordToken
                optional: false

          - name: AppSettings__BattleNetClientId
            valueFrom:
              secretKeyRef:
                name: battlenet-29k8ckd5g2
                key: clientid
                optional: false
          - name: AppSettings__BattleNetClientSecret
            valueFrom:
              secretKeyRef:
                name: battlenet-29k8ckd5g2
                key: clientsecret
                optional: false

          - name: DYSNOMIA_COMMON_STATS_CONNECTIONSTRING
            valueFrom:
              secretKeyRef:
                name: stats-writer-credentials-8ckkfd9ff2
                key: connectionstring
                optional: false
                
          - name: ASPNETCORE_HTTP_PORTS
            value: '80'

      imagePullSecrets:
      - name: github
