apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: achieve-games-database
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5

  bootstrap:
    initdb:
      database: achieve-games
      owner: achieve-games

  enableSuperuserAccess: true

  resources:
    requests:
      memory: "512Mi"
      cpu: 100m
    limits:
      memory: "5Gi"
      cpu: '2'

  storage:
    size: 30Gi
