apiVersion: apps/v1
kind: Deployment
metadata:
  name: achieve-games
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: achieve-games
  template:
    metadata:
      labels:
        app: achieve-games
    spec:
      containers:
      - image: ghcr.io/dysnomia-studio/achieve-games:1.5.0
        name: achieve-games
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 4000Mi
          limits:
            cpu: 2500m
            memory: 7000Mi
        env:
          - name: AppSettings__SteamAPIPublisherToken
            valueFrom:
              secretKeyRef:
                name: steam-2tkft4dc4c
                key: dysnomia-publisher-key
                optional: false
          - name: AppSettings__SteamWebAPIToken
            valueFrom:
              secretKeyRef:
                name: steam-2tkft4dc4c
                key: elanis-webapi-key
                optional: false

          - name: AppSettings__PG_USER
            valueFrom:
              secretKeyRef:
                name: achieve-games-database-app
                key: username
                optional: false
          - name: AppSettings__PG_HOST
            value: achieve-games-database-rw.achieve-games.svc.cluster.local
          - name: AppSettings__PG_DB
            valueFrom:
              secretKeyRef:
                name: achieve-games-database-app
                key: dbname
                optional: false
          - name: AppSettings__PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: achieve-games-database-app
                key: password
                optional: false

          - name: AppSettings__RedirectURI
            valueFrom:
              secretKeyRef:
                name: achieve-games-9thbfmmh29
                key: redirecturi
                optional: false
          - name: AppSettings__GithubToken
            valueFrom:
              secretKeyRef:
                name: achieve-games-9thbfmmh29
                key: githubtoken
                optional: false
          - name: AppSettings__DiscordToken
            valueFrom:
              secretKeyRef:
                name: achieve-games-9thbfmmh29
                key: discordToken
                optional: false

          - name: AppSettings__BattleNetClientId
            valueFrom:
              secretKeyRef:
                name: battlenet-29k8ckd5g2
                key: clientid
                optional: false
          - name: AppSettings__BattleNetClientSecret
            valueFrom:
              secretKeyRef:
                name: battlenet-29k8ckd5g2
                key: clientsecret
                optional: false
                
          - name: ASPNETCORE_HTTP_PORTS
            value: '80'

          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://$(NODE_IP):4317

      imagePullSecrets:
      - name: github
