apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc-n8n-data
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi