apiVersion: apps/v1
kind: Deployment
metadata:
  name: cours-m1
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: cours-m1
  template:
    metadata:
      labels:
        app: cours-m1
    spec:
      containers:
      - image: ghcr.io/dysnomia-studio/cours-m1-backend:main
        name: cours-m1
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1000m
            memory: 2000Mi
          limits:
            cpu: 2000m
            memory: 5000Mi
        env:
          - name: AppSettings__ConnectionString
            valueFrom:
              secretKeyRef:
                name: cours-m1-f4g46d95t6
                key: igdb-connectionstring
                optional: false
          - name: AppSettings__JwtKey
            valueFrom:
              secretKeyRef:
                name: cours-m1-f4g46d95t6
                key: igdb-jwtkey
                optional: false
          - name: AppSettings__JwtIssuer
            valueFrom:
              secretKeyRef:
                name: cours-m1-f4g46d95t6
                key: igdb-jwtissuer
                optional: false
          - name: AppSettings__IGDBClientSecret
            valueFrom:
              secretKeyRef:
                name: cours-m1-f4g46d95t6
                key: igdb-clientsecret
                optional: false
          - name: AppSettings__IGDBClientId
            valueFrom:
              secretKeyRef:
                name: cours-m1-f4g46d95t6
                key: igdb-clientid
                optional: false

          - name: DYSNOMIA_COMMON_STATS_CONNECTIONSTRING
            valueFrom:
              secretKeyRef:
                name: stats-writer-credentials-8ckkfd9ff2
                key: connectionstring
                optional: false
                
          - name: ASPNETCORE_HTTP_PORTS
            value: '80'

      imagePullSecrets:
      - name: github
