apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cours-m1-database
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2

  bootstrap:
    initdb:
      database: cours-m1
      owner: cours-m1

  enableSuperuserAccess: true

  resources:
    requests:
      memory: "512Mi"
      cpu: 100m
    limits:
      memory: "1Gi"
      cpu: '1'

  storage:
    size: 1Gi
