apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: games-dataminer-database
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3

  bootstrap:
    initdb:
      database: games-dataminer
      owner: games-dataminer

  enableSuperuserAccess: true

  resources:
    requests:
      memory: "512Mi"
      cpu: 500m
    limits:
      memory: "2Gi"
      cpu: '3'

  storage:
    size: 20Gi
