apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - image: ghcr.io/dysnomia-studio/redmine:main
        name: redmine
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 2000Mi
        env:
          - name: REDMINE_DB_POSTGRES
            value: redmine-database-rw.redmine.svc.cluster.local
          - name: REDMINE_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: redmine-database-app
                key: username
                optional: false
          - name: REDMINE_DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: redmine-database-app
                key: dbname
                optional: false
          - name: REDMINE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redmine-database-app
                key: password
                optional: false
          - name: REDMINE_PLUGINS_MIGRATE
            value: "1"
      imagePullSecrets:
      - name: github