apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: redmine-database
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2

  bootstrap:
    initdb:
      database: redmine
      owner: redmine

  enableSuperuserAccess: true

  resources:
    requests:
      memory: "512Mi"
      cpu: 100m
    limits:
      memory: "1Gi"
      cpu: '1'

  storage:
    size: 2Gi
