apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-demonset-collector
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: opentelemetry-collector
      repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      targetRevision: 0.126.0
      helm:
        values: |
          mode: daemonset

          image:
            repository: otel/opentelemetry-collector-contrib

          presets:
            # enables the k8sattributesprocessor and adds it to the traces, metrics, and logs pipelines
            kubernetesAttributes:
              enabled: true
            # enables the kubeletstatsreceiver and adds it to the metrics pipelines
            kubeletMetrics:
              enabled: true
            # Enables the filelogreceiver and adds it to the logs pipelines
            logsCollection:
              enabled: true
            # Enable host metrics
            hostMetrics:
              enabled: true

          config:
            receivers:
              otlp:
                protocols:
                  grpc:
                    endpoint: 0.0.0.0:4317
                  http:
                    endpoint: 0.0.0.0:4318
            exporters:
              debug:
                verbosity: detailed
              prometheus:
                endpoint: "0.0.0.0:11234"
                send_timestamps: true
                metric_expiration: 5m
                enable_open_metrics: true
                add_metric_suffixes: true
            service:
              pipelines:
                traces:
                  receivers:
                    - otlp
                  exporters:
                    - debug
                metrics:
                  receivers:
                    - otlp
                  exporters:
                    - debug
                logs:
                  receivers:
                    - otlp
                  exporters:
                    - debug
          ports:
            otlp:
              enabled: true
            otlp-http:
              enabled: true
            jaeger-compact:
              enabled: false
            jaeger-thrift:
              enabled: false
            jaeger-grpc:
              enabled: false
            zipkin:
              enabled: false
            metrics:
              enabled: false
            prom-metrics:
              enabled: true
              containerPort: 11234
              servicePort: 11234
              protocol: TCP

          resources:
            limits:
              cpu: 250m
              memory: 512Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring