apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.28.0
        imagePullPolicy: Always
        args:
          - "--config.file=/etc/alertmanager/config.yml"
          - "--storage.path=/alertmanager"
        ports:
        - name: alertmanager
          containerPort: 9093
        resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1000m
              memory: 1Gi
        volumeMounts:
        - name: config-volume-modified
          mountPath: /etc/alertmanager
        - name: alertmanager
          mountPath: /alertmanager
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "sed -e \"s|ALERTMANAGER_DISCORD_WEBHOOK|$ALERTMANAGER_DISCORD_WEBHOOK|g\" /etc/alertmanager-old/config.yml > /etc/alertmanager/config.yml"]
        env:
          - name: ALERTMANAGER_DISCORD_WEBHOOK
            valueFrom:
              secretKeyRef:
                name: alertmanager-cfb5gfd7m9
                key: discord_webhook
                optional: false
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager-old
        - name: config-volume-modified
          mountPath: /etc/alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager-config
      - name: config-volume-modified
        emptyDir: {}
      - name: alertmanager
        emptyDir: {}

