kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: discord
      group_wait: 10s
      repeat_interval: 1m
 
    receivers:
    - name: discord
      discord_configs:
      - webhook_url: 'ALERTMANAGER_DISCORD_WEBHOOK'
        send_resolved: true
        title: >-
          [{{ .Status | toUpper }}
          {{ if eq .Status "firing" }}: {{ .Alerts.Firing | len }}{{ end }}]
          {{ with (index .GroupLabels.SortedPairs.Values 0) }}
          {{ . }}
          {{ end }}
        message: |-
          {{ if and .Alerts.Firing (gt (len .Alerts.Firing) 0) }}
          {{- range .Alerts.Firing }}
          {{- if gt (len .Annotations) 0 }}
          {{ range .Annotations.SortedPairs }}
          - {{ .Name }}: {{ .Value }}
          {{- end }}
          {{- else }}
          (No Annotations)
          {{- end }}
          {{- end }}
          {{- end }}
