apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: ghcr.io/dysnomia-studio/grafana:main
        name: grafana
        ports:
        - containerPort: 3000
        env:
          - name: GF_INSTALL_PLUGINS
            value: 'petrslavotinek-carpetplot-panel'

          - name: DS_DMARCREPORTS_USERNAME
            valueFrom:
              secretKeyRef:
                name: grafana-bhc6hgmdk6
                key: username
                optional: false
          - name: DS_DMARCREPORTS_HOST
            value:  postgres.dysnomia-apps.svc.cluster.local
          - name: DS_DMARCREPORTS_DB
            value: dmarcreports
          - name: DS_DMARCREPORTS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-bhc6hgmdk6
                key: password
                optional: false

          - name: DS_LUMEN_USERNAME
            valueFrom:
              secretKeyRef:
                name: grafana-bhc6hgmdk6
                key: username
                optional: false
          - name: DS_LUMEN_HOST
            value:  postgres.dysnomia-apps.svc.cluster.local
          - name: DS_LUMEN_DB
            value: lumen
          - name: DS_LUMEN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-bhc6hgmdk6
                key: password
                optional: false

          - name: DS_REDMINE_USERNAME
            valueFrom:
              secretKeyRef:
                name: grafana-bhc6hgmdk6
                key: username
                optional: false
          - name: DS_REDMINE_HOST
            value:  postgres.dysnomia-apps.svc.cluster.local
          - name: DS_REDMINE_DB
            value: redmine
          - name: DS_REDMINE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-bhc6hgmdk6
                key: password
                optional: false

          - name: DS_STATS_USERNAME
            valueFrom:
              secretKeyRef:
                name: grafana-bhc6hgmdk6
                key: username
                optional: false
          - name: DS_STATS_HOST
            value:  postgres.dysnomia-apps.svc.cluster.local
          - name: DS_STATS_DB
            value: stats
          - name: DS_STATS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-bhc6hgmdk6
                key: password
                optional: false
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 150Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
      imagePullSecrets:
      - name: github