apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-app
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: authentik
      repoURL: https://charts.goauthentik.io
      targetRevision: 2026.2.1
      helm:
        values: |
          authentik:
            error_reporting:
              enabled: false
            log_level: info

          server:
            ingress:
              ingressClassName: traefik
              enabled: true
              hosts:
                - sso.dysnomia.studio

          global:
            env:
              - name: AUTHENTIK_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: authentik-app-secret-4gt2hfc2hh
                    key: secret_key

              - name: AUTHENTIK_POSTGRESQL__HOST
                value: authentik-database-rw.authentik-app.svc.cluster.local
              - name: AUTHENTIK_POSTGRESQL__PORT
                valueFrom:
                  secretKeyRef:
                    name: authentik-database-app
                    key: port
              - name: AUTHENTIK_POSTGRESQL__USER
                valueFrom:
                  secretKeyRef:
                    name: authentik-database-app
                    key: username
              - name: AUTHENTIK_POSTGRESQL__PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: authentik-database-app
                    key: password
              - name: AUTHENTIK_POSTGRESQL__NAME
                valueFrom:
                  secretKeyRef:
                    name: authentik-database-app
                    key: dbname
              - name: AUTHENTIK_POSTGRESQL__SSLMODE
                value: prefer

  destination:
    server: https://kubernetes.default.svc
    namespace: authentik-app
