apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: PR
              description: GitHub's Pull Requests to review
              href: https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3AElanis+user%3ADysnomia-Studio+user%3AL-U-M-E-N+archived%3Afalse+
  services.yaml: |
    - System dashboards:
        - ArgoCD:
            href: https://argocd-server.argocd.svc.cluster.local/
            description: ArgoCD dashboard
        - Longhorn:
            href: http://longhorn-frontend.longhorn-system.svc.cluster.local/
            description: Longhorn dashboard
        - Traefik:
            href: http://traefik-private.kube-system.svc.cluster.local/dashboard/
            description: Traefik dashboard
    - Apps:
        - Grafana:
            href: http://grafana.monitoring.svc.cluster.local/
            description: 📊 Stats 📈
        - N8N:
            href: http://n8n.n8n.svc.cluster.local/
            description: ⚙️ Automation
        - Redmine:
            href: https://bugs.dysnomia.studio
            description: Bug/Issues/Time tracker
        - Sonarqube:
            href: https://sonar.dysnomia.studio
            description: Code quality

    - Websites:
        - Achieve games:
            href: https://achieve.games/
            description: Achievements goes brrr
        - Dysnomia:
            href: https://dysnomia.studio
        - "Dysnomia's Wiki":
            href: https://wiki.dysnomia.studio
        - Galactae:
            href: https://galactae.eu
        - Gaspar:
            href: https://gaspar.ovh
        - Portfolio:
            href: https://elanis.eu
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - datetime:
        text_size: xl
        locale: fr
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
# Authentik
  docker.yaml: ""
