apiVersion: apps/v1
kind: Deployment
metadata:
  name: dehash-me
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: dehash-me
  template:
    metadata:
      labels:
        app: dehash-me
    spec:
      containers:
      - image: ghcr.io/dysnomia-studio/dehash-me:2.2.4
        name: dehash-me
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 25m
            memory: 250Mi
          limits:
            cpu: 1000m
            memory: 500Mi
        env:
          - name: PG_USER
            valueFrom:
              secretKeyRef:
                name: dehash-me-database-app
                key: username
                optional: false
          - name: PG_HOST
            value: dehash-me-database-rw.dehash-me.svc.cluster.local
          - name: PG_DB
            valueFrom:
              secretKeyRef:
                name: dehash-me-database-app
                key: dbname
                optional: false
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dehash-me-database-app
                key: password
                optional: false

          - name: ASPNETCORE_HTTP_PORTS
            value: '80'

          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://$(NODE_IP):4317
      imagePullSecrets:
      - name: github
