apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: lumen-server-database
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2

  bootstrap:
    initdb:
      database: lumen-server
      owner: lumen-server

  enableSuperuserAccess: true

  resources:
    requests:
      memory: "512Mi"
      cpu: 250m
    limits:
      memory: "1Gi"
      cpu: '2'

  storage:
    size: 5Gi
