apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumen-server
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: lumen-server
  template:
    metadata:
      labels:
        app: lumen-server
    spec:
      containers:
      - image: ghcr.io/l-u-m-e-n/lumen-server-docker-seafile-client:master
        name: lumen-server
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 1000Mi
          limits:
            cpu: 2000m
            memory: 4000Mi
        env:
          - name: LIBRARY_ID
            valueFrom:
              secretKeyRef:
                name: lumen-server-tkh56tgg99
                key: libraryId
                optional: false
          - name: SERVER_PORT
            value: "443"
          - name: SERVER_URL
            valueFrom:
              secretKeyRef:
                name: lumen-server-tkh56tgg99
                key: serverUrl
                optional: false
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: lumen-server-tkh56tgg99
                key: username
                optional: false
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: lumen-server-tkh56tgg99
                key: password
                optional: false

          - name: PG_USER
            valueFrom:
              secretKeyRef:
                name: lumen-server-database-app
                key: username
                optional: false
          - name: PG_HOST
            value: lumen-server-database-rw.lumen-server.svc.cluster.local
          - name: PG_DB
            valueFrom:
              secretKeyRef:
                name: lumen-server-database-app
                key: dbname
                optional: false
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lumen-server-database-app
                key: password
                optional: false
      imagePullSecrets:
      - name: github
