apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumen-server-v6
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: lumen-server-v6
  template:
    metadata:
      labels:
        app: lumen-server-v6
    spec:
      containers:
      - image: ghcr.io/dysnomia-studio/lumen-server:main
        name: lumen-server-v6
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 25m
            memory: 250Mi
          limits:
            cpu: 1000m
            memory: 500Mi
        env:
          - name: Modules__GoodReadsModule__GOODREADS_RSS_URL
            valueFrom:
              secretKeyRef:
                name: lumen-server-f2m98c8g22
                key: goodreads_RSSURL
                optional: false
          - name: Modules__NotABotModule__NAB_SERVER_LIST
            valueFrom:
              secretKeyRef:
                name: lumen-server-f2m98c8g22
                key: notabot_serverlist
                optional: false
          - name: Modules__YoutubeModule__PLAYLIST_ID
            valueFrom:
              secretKeyRef:
                name: lumen-server-f2m98c8g22
                key: youtube_PlaylistId
                optional: false
          - name: Modules__YoutubeModule__API_KEY
            valueFrom:
              secretKeyRef:
                name: lumen-server-f2m98c8g22
                key: youtube_APIKey
                optional: false
          - name: ApiKey
            valueFrom:
              secretKeyRef:
                name: lumen-server-f2m98c8g22
                key: apiKey
                optional: false

          - name: PG_USER
            valueFrom:
              secretKeyRef:
                name: lumen-server-database-app
                key: username
                optional: false
          - name: PG_HOST
            value: lumen-server-database-rw.lumen-server.svc.cluster.local
          - name: PG_DB
            valueFrom:
              secretKeyRef:
                name: lumen-server-database-app
                key: dbname
                optional: false
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lumen-server-database-app
                key: password
                optional: false
          - name: ASPNETCORE_HTTP_PORTS
            value: '80'
      imagePullSecrets:
      - name: github
