apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumen-server
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: lumen-server
  template:
    metadata:
      labels:
        app: lumen-server
    spec:
      containers:
      - image: ghcr.io/l-u-m-e-n/lumen-server-docker-seafile-client:master
        name: lumen-server
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
            memory: 500Mi
          limits:
            cpu: 2000m
            memory: 3500Mi
        env:
          - name: LIBRARY_ID
            valueFrom:
              secretKeyRef:
                name: lumen-server-k6mgf92mch
                key: libraryId
                optional: false
          - name: SERVER_PORT
            value: "443"
          - name: SERVER_URL
            valueFrom:
              secretKeyRef:
                name: lumen-server-k6mgf92mch
                key: serverUrl
                optional: false
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: lumen-server-k6mgf92mch
                key: username
                optional: false
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: lumen-server-k6mgf92mch
                key: password
                optional: false
      imagePullSecrets:
      - name: github
