apiVersion: apps/v1
kind: Deployment
metadata:
  name: factory-server-ptb
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: factory-server-ptb
  template:
    metadata:
      labels:
        app: factory-server-ptb
    spec:
      containers:
      - image: ghcr.io/dysnomia-studio/factory-game-server:0.3.4
        name: factory-server-ptb
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1000m
            memory: 250Mi
          limits:
            cpu: 1500m
            memory: 750Mi
        env:
          - name: PUBLISHER_KEY
            valueFrom:
              secretKeyRef:
                name: steam-2h7c6httht
                key: dysnomia-publisher-key
                optional: false

          - name: PG_USER
            valueFrom:
              secretKeyRef:
                name: factory-server-ptb-database-app
                key: username
                optional: false
          - name: PG_HOST
            value: factory-server-ptb-database-rw.factory-server-ptb.svc.cluster.local
          - name: PG_DB
            valueFrom:
              secretKeyRef:
                name: factory-server-ptb-database-app
                key: dbname
                optional: false
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: factory-server-ptb-database-app
                key: password
                optional: false

          - name: UNIT_TEST_CLIENT_TOKEN
            valueFrom:
              secretKeyRef:
                name: unit-test-dfdmgfcgfd
                key: key
                optional: false
          - name: IS_DEV
            value: 'true'

      imagePullSecrets:
      - name: github