apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: factory-server-ptb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: factory-server-ptb
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50