apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: factory-server-ptb-database
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1

  bootstrap:
    initdb:
      database: factory-server-ptb
      owner: factory-server-ptb

  enableSuperuserAccess: true

  resources:
    requests:
      memory: "512Mi"
      cpu: 100m
    limits:
      memory: "1Gi"
      cpu: '2'

  storage:
    size: 1Gi
