apiVersion: apps/v1
kind: Deployment
metadata:
  name: factory-server-prod
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: factory-server-prod
  template:
    metadata:
      labels:
        app: factory-server-prod
    spec:
      containers:
      - image: ghcr.io/dysnomia-studio/factory-game-server:develop
        name: factory-server-prod
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1000m
            memory: 250Mi
          limits:
            cpu: 1500m
            memory: 750Mi
        env:
          - name: PUBLISHER_KEY
            valueFrom:
              secretKeyRef:
                name: steam-2h7c6httht
                key: dysnomia-publisher-key
                optional: false

          - name: PG_USER
            valueFrom:
              secretKeyRef:
                name: factory-server-prod-database-app
                key: username
                optional: false
          - name: PG_HOST
            value: factory-server-prod-database-rw.factory-server-prod.svc.cluster.local
          - name: PG_DB
            valueFrom:
              secretKeyRef:
                name: factory-server-prod-database-app
                key: dbname
                optional: false
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: factory-server-prod-database-app
                key: password
                optional: false

      imagePullSecrets:
      - name: github