apiVersion: apps/v1
kind: Deployment
metadata:
  name: factory-server-prod
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: factory-server-prod
  template:
    metadata:
      labels:
        app: factory-server-prod
    spec:
      containers:
      - image: ghcr.io/dysnomia-studio/factory-game-server:develop
        name: factory-server-prod
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
            memory: 50Mi
          limits:
            cpu: 1000m
            memory: 500Mi
        env:
          - name: PUBLISHER_KEY
            valueFrom:
              secretKeyRef:
                name: steam-hdcdk47mmg
                key: dysnomia-publisher-key
                optional: false
          - name: APP_ID
            valueFrom:
              secretKeyRef:
                name: steam-hdcdk47mmg
                key: factory-appid
                optional: false

          - name: PG_USER
            valueFrom:
              secretKeyRef:
                name: factory-server-prod-database-58b5fgtfkb
                key: username
                optional: false
          - name: PG_HOST
            valueFrom:
              secretKeyRef:
                name: factory-server-prod-database-58b5fgtfkb
                key: hostname
                optional: false
          - name: PG_DB
            valueFrom:
              secretKeyRef:
                name: factory-server-prod-database-58b5fgtfkb
                key: database
                optional: false
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: factory-server-prod-database-58b5fgtfkb
                key: password
                optional: false

      imagePullSecrets:
      - name: github