apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: factory-server-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: factory-server-prod
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50