apiVersion: apps/v1
kind: Deployment
metadata:
  name: galactae-server-00
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: galactae-server-00
  template:
    metadata:
      labels:
        app: galactae-server-00
    spec:
      containers:
      - image: ghcr.io/dysnomia-studio/galactae-server:develop
        name: galactae-server-00
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 5m
            memory: 75Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        env:
          - name: GALACTAE_00_SQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: galactae-00-9ffbtbgd87
                key: username
                optional: false
          - name: GALACTAE_00_SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: galactae-00-9ffbtbgd87
                key: hostname
                optional: false
          - name: GALACTAE_00_SQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: galactae-00-9ffbtbgd87
                key: database
                optional: false
          - name: GALACTAE_00_SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: galactae-00-9ffbtbgd87
                key: password
                optional: false

          - name: GALACTAE_SQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: galactae-website-mtckh984h5
                key: username
                optional: false
          - name: GALACTAE_SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: galactae-website-mtckh984h5
                key: hostname
                optional: false
          - name: GALACTAE_SQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: galactae-website-mtckh984h5
                key: database
                optional: false
          - name: GALACTAE_SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: galactae-website-mtckh984h5
                key: password
                optional: false

          - name: GALACTAE_DISCORD_TOKEN
            valueFrom:
              secretKeyRef:
                name: galactae-server-7gf6hgtdgg
                key: discord-token
                optional: false

          - name: GALACTAE_ADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: galactae-server-7gf6hgtdgg
                key: adminUsername
                optional: false   

          - name: GALACTAE_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: galactae-server-7gf6hgtdgg
                key: adminPassword
                optional: false  

        volumeMounts:
        - name: galactae-server-00-config
          mountPath: "/app/config/"
          readOnly: true

      imagePullSecrets:
      - name: github
      volumes:
      - name: galactae-server-00-config
        configMap:
          name: galactae-server-00-config