apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: galactae-subdomains-tls-secret
spec:
  secretName: galactae-subdomains-tls-secret-secret
  dnsNames:
    - cdn.galactae.eu
    - 00-dev.galactae.eu
    - 01-milkyway.galactae.eu
    - 00-srv.galactae.eu
    - 01-srv.galactae.eu
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer