apiVersion: apps/v1
kind: Deployment
metadata:
  name: galactae-client-00
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: galactae-client-00
  template:
    metadata:
      labels:
        app: galactae-client-00
    spec:
      containers:
      - image: ghcr.io/dysnomia-studio/galactae-client:Beta-0.10.7-rev.250401a
        name: galactae-client-00
        ports:
        - containerPort: 80
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "bash /var/www/applyEnvVariables.sh"]
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 5m
            memory: 75Mi
          limits:
            cpu: 300m
            memory: 1000Mi
        env:
          - name: GALACTAE_SQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: galactae-main-database-app
                key: username
                optional: false
          - name: GALACTAE_SQL_SERVER
            value: galactae-main-database-rw.galactae.svc.cluster.local
          - name: GALACTAE_SQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: galactae-main-database-app
                key: dbname
                optional: false
          - name: GALACTAE_SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: galactae-main-database-app
                key: password
                optional: false
          
          - name: GALACTAE_00_SQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: galactae-00-database-app
                key: username
                optional: false
          - name: GALACTAE_00_SQL_SERVER
            value: galactae-00-database-rw.galactae.svc.cluster.local
          - name: GALACTAE_00_SQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: galactae-00-database-app
                key: dbname
                optional: false
          - name: GALACTAE_00_SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: galactae-00-database-app
                key: password
                optional: false
        volumeMounts:
        - name: galactae-client-00-config
          mountPath: "/var/www/config/"
          readOnly: true

        - name: galactae-client-00-config
          mountPath: "/var/www/app/views/gvars/"
          readOnly: true

      imagePullSecrets:
      - name: github
      volumes:
      - name: galactae-client-00-config
        configMap:
          name: galactae-client-00-config