apiVersion: apps/v1
kind: Deployment
metadata:
  name: galactae-client-00
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: galactae-client-00
  template:
    metadata:
      labels:
        app: galactae-client-00
    spec:
      containers:
      - image: ghcr.io/dysnomia-studio/galactae-client:develop
        name: galactae-client-00
        ports:
        - containerPort: 80
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "bash /var/www/applyEnvVariables.sh"]
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 5m
            memory: 75Mi
          limits:
            cpu: 300m
            memory: 1000Mi
        env:
          - name: GALACTAE_SQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: galactae-website-mtckh984h5
                key: username
                optional: false
          - name: GALACTAE_SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: galactae-website-mtckh984h5
                key: hostname
                optional: false
          - name: GALACTAE_SQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: galactae-website-mtckh984h5
                key: database
                optional: false
          - name: GALACTAE_SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: galactae-website-mtckh984h5
                key: password
                optional: false
          
          - name: GALACTAE_00_SQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: galactae-00-9ffbtbgd87
                key: username
                optional: false
          - name: GALACTAE_00_SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: galactae-00-9ffbtbgd87
                key: hostname
                optional: false
          - name: GALACTAE_00_SQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: galactae-00-9ffbtbgd87
                key: database
                optional: false
          - name: GALACTAE_00_SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: galactae-00-9ffbtbgd87
                key: password
                optional: false

          - name: STATS_SQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: stats-writer-credentials-8ckkfd9ff2
                key: username
                optional: false
          - name: STATS_SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: stats-writer-credentials-8ckkfd9ff2
                key: hostname
                optional: false
          - name: STATS_SQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: stats-writer-credentials-8ckkfd9ff2
                key: database
                optional: false
          - name: STATS_SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: stats-writer-credentials-8ckkfd9ff2
                key: password
                optional: false

        volumeMounts:
        - name: galactae-client-00-config
          mountPath: "/var/www/config/"
          readOnly: true

        - name: galactae-client-00-config
          mountPath: "/var/www/app/views/gvars/"
          readOnly: true

      imagePullSecrets:
      - name: github
      volumes:
      - name: galactae-client-00-config
        configMap:
          name: galactae-client-00-config