apiVersion: apps/v1
kind: Deployment
metadata:
  name: galactae-website
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: galactae-website
  template:
    metadata:
      labels:
        app: galactae-website
    spec:
      containers:
      - image: ghcr.io/dysnomia-studio/galactae-website:main
        name: galactae-website
        ports:
        - containerPort: 80
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "bash /var/www/applyEnvVariables.sh"]
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 5m
            memory: 75Mi
          limits:
            cpu: 300m
            memory: 1000Mi
        env:
          - name: GALACTAE_SQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: galactae-website-f25h98dgd8
                key: username
                optional: false
          - name: GALACTAE_SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: galactae-website-f25h98dgd8
                key: hostname
                optional: false
          - name: GALACTAE_SQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: galactae-website-f25h98dgd8
                key: database
                optional: false
          - name: GALACTAE_SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: galactae-website-f25h98dgd8
                key: password
                optional: false

          - name: MAIL_SERVER
            valueFrom:
              secretKeyRef:
                name: galactae-website-f25h98dgd8
                key: mail-server
                optional: false

          - name: MAIL_USERNAME
            valueFrom:
              secretKeyRef:
                name: galactae-website-f25h98dgd8
                key: mail-username
                optional: false

          - name: MAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: galactae-website-f25h98dgd8
                key: mail-password
                optional: false

          - name: STATS_SQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: stats-writer-credentials-8ckkfd9ff2
                key: username
                optional: false
          - name: STATS_SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: stats-writer-credentials-8ckkfd9ff2
                key: hostname
                optional: false
          - name: STATS_SQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: stats-writer-credentials-8ckkfd9ff2
                key: database
                optional: false
          - name: STATS_SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: stats-writer-credentials-8ckkfd9ff2
                key: password
                optional: false

        volumeMounts:
        - name: galactae-website-config
          mountPath: "/var/www/config/"
          readOnly: true
      imagePullSecrets:
      - name: github
      volumes:
      - name: galactae-website-config
        configMap:
          name: galactae-website-config