apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: galactae-01-database
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5

  bootstrap:
    initdb:
      database: galactae-01
      owner: galactae-01

  enableSuperuserAccess: true

  resources:
    requests:
      memory: "512Mi"
      cpu: 25m
    limits:
      memory: "1Gi"
      cpu: '1'

  storage:
    size: 3Gi