apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: galactae-00-database
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.7

  bootstrap:
    initdb:
      database: galactae-00
      owner: galactae-00

  enableSuperuserAccess: true

  resources:
    requests:
      memory: "512Mi"
      cpu: 25m
    limits:
      memory: "1Gi"
      cpu: '1'

  storage:
    size: 3Gi
